// node tools/icons/build.mjs [--check]  ->  web/icons.js
// Turns the SVG files of web/icons/ into one script: NurvanIcons.svg('close') gives the inline <svg>, and a small
// sweeper replaces the emoji and symbols the app writes in its text with the matching icon (so the ~300 places
// that wrote 📅 or ✕ need no edit). Generated: never edit web/icons.js by hand.
import fs from 'node:fs';
import path from 'node:path';
import { ICONS, GRIDS, COLORS } from './manifest.mjs';

const dir = 'web/icons';
const OUT = 'web/icons.js';

// Glyphs that are replaced only when they stand at the start or the end of their text (a button label), because
// in the middle of a sentence they are punctuation or an arrow with a meaning of its own.
const EDGE_ONLY = new Set(['✕', '✓', '✎', '▾', '▸', '▶', '◀', 'ⓘ', '⚠', '⚙', '✅', '➕']);
// Emoji whose icon is not good enough yet (to be redrawn): they stay as they are until the file is replaced.
const HOLD = new Set([]);
// Symbols that are used as plain arrows in the text of the app: never replaced.
const NEVER = new Set(['→', '↑', '↓']);

const glyphs = {};
for (const icon of ICONS) {
  if (HOLD.has(icon.id)) continue;
  for (const g of String(icon.replaces || '').split(/\s+/).filter(Boolean)) {
    if (NEVER.has(g) || g === '+') continue;
    if (!glyphs[g]) glyphs[g] = icon.id;
  }
}

const data = {};
for (const icon of ICONS) {
  const file = path.join(dir, icon.id + '.svg');
  if (!fs.existsSync(file)) continue;
  const src = fs.readFileSync(file, 'utf8').trim();
  const inner = src.replace(/^<svg\b[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  data[icon.id] = [GRIDS[icon.grid].viewBox, GRIDS[icon.grid].stroke, inner];
}
// An emoji whose own icon is not drawn yet borrows the nearest one until the file exists (first available wins).
const FALLBACK = { '📍': ['map-pin', 'target'], '💎': ['diamond', 'wallet'], '🎓': ['graduation-cap', 'book'], '💡': ['lightbulb', 'info'], '🧩': ['puzzle', 'library'], '🧭': ['compass', 'target'], '📄': ['document', 'clipboard'], '🔬': ['microscope', 'module-exams'] };
for (const g of Object.keys(glyphs)) if (!data[glyphs[g]]) delete glyphs[g];
for (const [g, list] of Object.entries(FALLBACK)) { const id = list.find((n) => data[n]); if (id) glyphs[g] = id; }
const colors = {};
for (const id of Object.keys(data)) if (COLORS[id]) colors[id] = COLORS[id];

const code = `/* GENERATED by tools/icons/build.mjs from web/icons/*.svg - do not edit by hand. */
(function () {
  'use strict';
  var DATA = ${JSON.stringify(data)};
  var GLYPHS = ${JSON.stringify(glyphs)};
  var EDGE = ${JSON.stringify([...EDGE_ONLY])};
  var COLORS = ${JSON.stringify(colors)};

  // The inline <svg> of an icon, in the colour of the text around it.
  function svg(name, size, extra) {
    var d = DATA[name];
    if (!d) return '';
    var px = size ? ' width="' + size + '" height="' + size + '"' : '';
    return '<svg class="nv-ic' + (extra ? ' ' + extra : '') + '" data-ic="' + name + '" viewBox="' + d[0] + '" stroke-width="' + d[1] + '"' + px + ' aria-hidden="true" focusable="false">' + d[2] + '</svg>';
  }
  function has(name) { return !!DATA[name]; }

  var keys = Object.keys(GLYPHS).sort(function (a, b) { return b.length - a.length; });
  var esc = function (s) { return s.replace(/[.*+?^$\\{}()|[\\]\\\\]/g, '\\\\$&'); };
  var RE = keys.length ? new RegExp('(' + keys.map(esc).join('|') + ')\\\\uFE0F?', 'gu') : null;
  var SKIP = 'script,style,textarea,input,option,select,title,svg,noscript,[data-noicon],[contenteditable="true"]';

  function convert(node) {
    var text = node.nodeValue;
    if (!RE || !text) return;
    RE.lastIndex = 0;
    if (!RE.test(text)) return;
    var parent = node.parentNode;
    if (!parent || (parent.closest && parent.closest(SKIP))) return;
    RE.lastIndex = 0;
    var frag = document.createDocumentFragment();
    var last = 0, changed = false, m;
    var trimmed = text.replace(/^\\s+|\\s+$/g, '');
    while ((m = RE.exec(text))) {
      var g = m[1];
      var atStart = text.slice(0, m.index).replace(/\\s+/g, '') === '';
      var atEnd = text.slice(m.index + m[0].length).replace(/\\s+/g, '') === '';
      if (EDGE.indexOf(g) >= 0 && !(atStart || atEnd)) continue;
      if (m.index > last) frag.appendChild(document.createTextNode(text.slice(last, m.index)));
      var span = document.createElement('span');
      span.className = 'nv-gl';
      span.innerHTML = svg(GLYPHS[g]);
      frag.appendChild(span);
      last = m.index + m[0].length;
      changed = true;
    }
    if (!changed) return;
    if (last < text.length) frag.appendChild(document.createTextNode(text.slice(last)));
    parent.replaceChild(frag, node);
  }

  function sweep(root) {
    if (!root || !document.createTreeWalker) return;
    var base = root.nodeType === 3 ? root.parentNode : root;
    if (!base) return;
    var walker = document.createTreeWalker(base, 4, null);
    var nodes = [], n;
    while ((n = walker.nextNode())) { if (n.nodeValue && RE && (RE.lastIndex = 0, RE.test(n.nodeValue))) nodes.push(n); }
    nodes.forEach(convert);
  }

  var timer = 0;
  function later() {
    clearTimeout(timer);
    // After the language sweeper has had its turn on the new text.
    timer = setTimeout(function () { sweep(document.body); }, 120);
  }
  function start() {
    if (!document.body || typeof MutationObserver !== 'function') return;
    sweep(document.body);
    new MutationObserver(later).observe(document.body, { childList: true, subtree: true, characterData: true });
  }
  // One colour per icon that names a thing; the small actions take the colour of their text.
  function paint() {
    var css = Object.keys(COLORS).map(function (k) { return '.nv-ic[data-ic="' + k + '"]{color:' + COLORS[k] + '}'; }).join('');
    css += '.btn-primary .nv-ic,.pill-tab.active .nv-ic,.nv-mono .nv-ic,.nav-item .nv-ic{color:inherit !important}';
    var el = document.createElement('style');
    el.setAttribute('data-nv-icons', '1');
    el.textContent = css;
    document.head.appendChild(el);
  }
  if (typeof document !== 'undefined' && document.head) paint();
  window.NurvanIcons = { svg: svg, has: has, sweep: sweep, glyphs: GLYPHS };
  if (typeof document !== 'undefined' && document.addEventListener) {
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start); else start();
  }
})();
`;

if (process.argv.includes('--check')) {
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (have !== code) { console.log('web/icons.js is not up to date: run node tools/icons/build.mjs'); process.exit(1); }
  console.log('web/icons.js is up to date (' + Object.keys(data).length + ' icons, ' + Object.keys(glyphs).length + ' glyphs).');
} else {
  // A temporary file and a rename: Windows now and then refuses a direct write while the preview server reads the file.
  fs.writeFileSync(OUT + '.tmp', code);
  fs.renameSync(OUT + '.tmp', OUT);
  console.log('written ' + OUT + ': ' + Object.keys(data).length + ' icons, ' + Object.keys(glyphs).length + ' glyphs mapped.');
}
