// The references of "Salute e recupero" (web/wellbeing.js, web/wellbeing-care.js).
//
//   node tools/build_wellbeing_refs.mjs          write web/wellbeing-refs.js
//   node tools/build_wellbeing_refs.mjs --check  no network: every reference the texts cite is in the file
//
// A citation shown in the app is never typed by hand: the PubMed identifiers
// found in the two content files are asked of PubMed (E-utilities), and the
// authors, year, title and journal come from there. Guidelines that are not on
// PubMed are listed below with their official title and address.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const OUT = path.join(ROOT, 'web/wellbeing-refs.js');
const FILES = ['web/wellbeing.js', 'web/wellbeing-care.js'];

const OFFICIAL = {
  'nice-ng59': { cite: 'NICE. Low back pain and sciatica in over 16s: assessment and management. NICE guideline NG59. 2016 (aggiornata)', url: 'https://www.nice.org.uk/guidance/ng59' },
  'nice-ng192': { cite: 'NICE. Caesarean birth. NICE guideline NG192. 2021', url: 'https://www.nice.org.uk/guidance/ng192' },
  'nice-ng194': { cite: 'NICE. Postnatal care. NICE guideline NG194. 2021', url: 'https://www.nice.org.uk/guidance/ng194' },
  'nice-ng210': { cite: 'NICE. Pelvic floor dysfunction: prevention and non-surgical management. NICE guideline NG210. 2021', url: 'https://www.nice.org.uk/guidance/ng210' },
  'nice-ng235': { cite: 'NICE. Intrapartum care. NICE guideline NG235. 2023', url: 'https://www.nice.org.uk/guidance/ng235' },
  'rcog-gtg29': { cite: 'RCOG. The Management of Third- and Fourth-Degree Perineal Tears. Green-top Guideline No. 29. 2015', url: 'https://www.rcog.org.uk/media/5jeb5hzu/gtg-29.pdf' },
  'goom-2019': { cite: 'Goom T, Donnelly G, Brockwell E. Returning to running postnatal: guidelines for medical, health and fitness professionals managing this population. 2019 (documento di esperti, non indicizzato su PubMed)', url: 'https://www.absolute.physio/wp-content/uploads/2019/09/returning-to-running-postnatal-guidelines.pdf' },
  'uk-cmo-postpartum': { cite: 'UK Chief Medical Officers. Physical activity for women after childbirth (birth to 12 months). UK CMO Physical Activity Guidelines, 2019', url: 'https://assets.publishing.service.gov.uk/media/620a2ff9d3bf7f4f0ec9b574/postpartum_infographic.pdf' },
  'who-lbp-2023': { cite: 'World Health Organization. WHO guideline for non-surgical management of chronic primary low back pain in adults in primary and community care settings. 2023', url: 'https://www.who.int/publications/i/item/9789240081789' }
};

// Every reference id the content files cite: "r: [ ... ]" lists.
export function citedIds() {
  const ids = new Set();
  for (const f of FILES) {
    const text = fs.readFileSync(path.join(ROOT, f), 'utf8');
    for (const m of text.matchAll(/\br: \[([^\]]*)\]/g)) for (const q of m[1].matchAll(/"([^"]+)"/g)) ids.add(q[1]);
  }
  return [...ids];
}
const isPmid = (id) => /^\d{5,9}$/.test(id);

function cite(x) {
  const names = x.authors.map((a) => a.name);
  const who = names.length > 3 ? names.slice(0, 3).join(', ') + ' et al' : (names.join(', ') || 'American College of Obstetricians and Gynecologists');
  const year = (String(x.pubdate).match(/\d{4}/) || [''])[0];
  const title = String(x.title).replace(/\.$/, '');
  const where = x.source + (x.volume ? ' ' + x.volume + (x.issue ? '(' + x.issue + ')' : '') + (x.pages ? ':' + x.pages : '') : '');
  return who + '. ' + year + '. ' + title + '. ' + where;
}

const ids = citedIds();
if (process.argv.includes('--check')) {
  const built = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  const missing = ids.filter((id) => !built.includes('"' + id + '":'));
  if (missing.length) { console.log('Missing references:', missing.join(', ')); process.exit(1); }
  console.log(ids.length + ' references, all in web/wellbeing-refs.js');
  process.exit(0);
}

const refs = {};
const pmids = ids.filter(isPmid);
for (let i = 0; i < pmids.length; i += 80) {
  const chunk = pmids.slice(i, i + 80);
  const res = await fetch('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pubmed&retmode=json&id=' + chunk.join(','));
  const json = await res.json();
  for (const id of chunk) {
    const x = json.result[id];
    if (!x || x.error) throw new Error('PubMed has no record ' + id);
    refs[id] = { cite: cite(x), pmid: id, url: 'https://pubmed.ncbi.nlm.nih.gov/' + id + '/' };
  }
  await new Promise((r) => setTimeout(r, 400));
}
for (const id of ids.filter((x) => !isPmid(x))) {
  if (!OFFICIAL[id]) throw new Error('No official entry for ' + id);
  refs[id] = OFFICIAL[id];
}
const sorted = Object.fromEntries(Object.keys(refs).sort().map((k) => [k, refs[k]]));
fs.writeFileSync(OUT, '// Generated by tools/build_wellbeing_refs.mjs from PubMed. Do not edit.\nself.NURVAN_WELLBEING_REFS = ' + JSON.stringify(sorted, null, 1) + ';\n', 'utf8');
console.log(Object.keys(sorted).length + ' references written');
for (const k of Object.keys(sorted)) console.log(k.padEnd(10), sorted[k].cite.slice(0, 120));
